# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build CV and send mail

on: push

jobs:
  build_pdf:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: xu-cheng/latex-action@v3
      with:
        root_file: cv/cv.tex
        latexmk_use_lualatex: true

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: CV
        path: cv/cv.pdf

  send_mail:
    needs: build_pdf
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Download PDF artifact
      uses: actions/download-artifact@v2
      with:
        name: CV
        path: cv/cv.pdf

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'

    - run: npm ci

    - name: Send mail
      env:
        APP_EMAIL: ${{ secrets.APP_EMAIL }}
        APP_PWD: ${{ secrets.APP_PWD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: set -o allexport && . ./.env && set +o allexport && node index.js
